#pragma once

enum DetectionFlags {
    CODE_INTEGRITY,
    DLL_TAMPERING,
    BAD_IAT,
    OPEN_PROCESS_HANDLES,
    UNSIGNED_DRIVERS,
    INJECTED_SUSPECT_MODULE,
    EXTERNAL_SUSPECT_PROGRAM,
    MANUAL_MAPPING,
    SUSPENDED_THREAD,
    REMOTE_THREAD_CREATION,
    HYPERVISOR
};